name: 'Terragrunt Build and Test'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - run: cd gcp/example/test && go mod init gcp_example_test.go; go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.54
        working-directory: gcp/example/test
        skip-pkg-cache: true

    - name: Check documentation
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        fail-on-diff: true
        output-method: print
        working-dir: modules
